import type { Material } from "../types/material"

export const addonMaterials_batch11Part2: Material[] = [
  {
    "id": "addon_257",
    "name": "柏油路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_258",
    "name": "桥架安装50*50*1.2mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_259",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_260",
    "name": "移桩线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 25.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_261",
    "name": "立柱安装人工费（客户提供）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_262",
    "name": "立柱水泥基础（≥300*200*200mm）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_263",
    "name": "额外上门服务",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_264",
    "name": "高空作业（>5米）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_265",
    "name": "充电桩立柱混凝土基础浇筑",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_266",
    "name": "吊筋敷设",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_267",
    "name": "墙面开槽及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_268",
    "name": "套管升级 镀锌管JDG25",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 7.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_269",
    "name": "套管升级 镀锌管JDG32",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 13.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_270",
    "name": "套餐内升级电缆 3*6升3*10",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_271",
    "name": "套餐内升级电缆 5*6升5*10",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_272",
    "name": "安装开孔 ≤35mm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_273",
    "name": "工作接地",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_274",
    "name": "承重路面 沥青路/柏油路",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_275",
    "name": "更换漏保 三相20A/40A AC型",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  }
]
