import { Material } from '../types/material'

export const addonMaterials_batch5: Material[] = [
  {
    "id": "addon_146",
    "name": "12位PC阻燃漏保盒（含安装）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_147",
    "name": "2P 40A漏保开关（施耐德/ABB/西门子）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_148",
    "name": "2P 40A漏保开关（正泰/德力西等）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 26.8,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_149",
    "name": "2P 40A空开（施耐德/ABB/西门子）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_150",
    "name": "2P 40A空开（正泰/德力西等）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_151",
    "name": "3*6mm²升级至3*10mm²线缆",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_152",
    "name": "3*6mm²升级至3*16mm²线缆",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_153",
    "name": "4P 40A漏保开关（施耐德/ABB/西门子）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_154",
    "name": "4P 40A漏保开关（正泰/德力西等）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_155",
    "name": "4P 40A空开（施耐德/ABB/西门子）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_156",
    "name": "4P 40A空开（正泰/德力西等）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_157",
    "name": "5*6mm²升级至5*10mm²线缆",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_158",
    "name": "5*6mm²升级至5*16mm²线缆",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 750.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_159",
    "name": "8位PC阻燃漏保盒（含安装）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_160",
    "name": "三相380V普通电表（含表箱及安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_161",
    "name": "上门勘测/检测等上门费用",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_162",
    "name": "仅线缆敷设人工费（用户自购线缆和套管）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_163",
    "name": "充电桩保护箱（厚度>0.8mm冷轧钢，含安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_164",
    "name": "充电桩拆除/安装及上门费用（客户原因）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_165",
    "name": "充电桩本体和漏保（盒）拆除（不含墙面复原）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_166",
    "name": "充电桩水泥基础（>=350*350*350mm，含预埋螺栓）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_167",
    "name": "充电桩立柱/保护箱/灭火器等安装费（逐个）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_168",
    "name": "充电桩立柱（高度>1.5m冷轧钢，含安装）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_169",
    "name": "单相220V普通电表（含表箱及安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_170",
    "name": "吊筋敷设（含材料及人工）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_171",
    "name": "墙体开孔（非承重墙，孔径32mm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_172",
    "name": "接地极（08圆钢或角钢埋深>1米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_173",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_174",
    "name": "桥架安装（规格50*50mm）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_175",
    "name": "水泥/地砖/柏油路等硬质路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_176",
    "name": "特殊安装地点服务费（景区/岛屿等）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_177",
    "name": "线缆拆除（不含墙面复原）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_178",
    "name": "线缆敷设 ZC-YJV-3*10mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_179",
    "name": "线缆敷设 ZC-YJV-3*16mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_180",
    "name": "线缆敷设 ZC-YJV-3*6mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_181",
    "name": "线缆敷设 ZC-YJV-5*10mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_182",
    "name": "线缆敷设 ZC-YJV-5*16mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_183",
    "name": "线缆敷设 ZC-YJV-5*6mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_184",
    "name": "高空作业（电缆敷设高度超过5米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  }
]
