import type { Material } from "../types/material"

export const addonMaterials_batch11Part1: Material[] = [
  {
    "id": "addon_238",
    "name": "保护箱安装人工费（客户提供）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_239",
    "name": "充电桩保护箱（600*500*250mm）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_240",
    "name": "充电桩桩体拆除",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_241",
    "name": "充电桩桩体挂桩",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_242",
    "name": "充电桩立柱（冷轧钢≥1.5m）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_243",
    "name": "充电桩线缆拆除",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_244",
    "name": "单相电表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 280.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_245",
    "name": "吊筋敷设（含材料及人工）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_246",
    "name": "墙体开孔>40cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_247",
    "name": "墙体开孔≤40cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_248",
    "name": "套包内线缆升级3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_249",
    "name": "套包内线缆升级3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_250",
    "name": "套包外电缆敷设3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_251",
    "name": "套包外电缆敷设3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_252",
    "name": "套包外电缆敷设3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_253",
    "name": "安装服务套包（30米线缆敷设）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 1350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_254",
    "name": "接地极（Ø8圆钢埋深>1米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_255",
    "name": "断路器安装（正泰/德力西40A）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_256",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "捷途",
    "freeQuota": 0,
    "source": "addon"
  }
]
