import type { Material } from "../types/material"

export const addonMaterials_batch6Part1: Material[] = [
  {
    "id": "addon_185",
    "name": "上门服务费 偏远地区",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "公里",
    "costPrice": 0,
    "settlementPrice": 1.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_186",
    "name": "上门服务费 其他三四线城市",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_187",
    "name": "上门服务费 省会/一二线",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_188",
    "name": "代理电力报装",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_189",
    "name": "充电桩立柱(含安装)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_190",
    "name": "墙面开槽及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_191",
    "name": "套包内电缆升级",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_192",
    "name": "拆移桩服务 原线缆拆除",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_193",
    "name": "拆移桩服务 原设备拆除",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_194",
    "name": "拆移桩服务 新设备安装",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_195",
    "name": "拆移桩服务 线缆敷设(旧电缆)",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_196",
    "name": "接地极",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_197",
    "name": "断路器保护盒 5/6位",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_198",
    "name": "断路器保护盒 8/12位",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_199",
    "name": "漏电断路器 11KW(380V/4P,20A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_200",
    "name": "漏电断路器 21KW(380V/4P,40A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_201",
    "name": "漏电断路器 7KW(220V/2P,40A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_202",
    "name": "电源点空开(63A)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_203",
    "name": "电缆敷设(三项) YJV-5*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_204",
    "name": "电缆敷设(三项) YJV-5*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  }
]
