import { Material } from '../types/material'

export const addonMaterials_batch14: Material[] = [
  {
    "id": "addon_224",
    "name": "30米套包内线缆升级至3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_225",
    "name": "专业开孔（砖墙/混凝土，限墙厚40cm/洞径11cm以下）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_226",
    "name": "充电桩保护箱（不锈钢 600*800*250mm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_227",
    "name": "充电桩立柱混凝土基础浇筑（350*350*200mm，含挖坑/立柱安装）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 260.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_228",
    "name": "喷塑桥架安装（50*50*1.2mm，含材料及人工）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_229",
    "name": "承重路开挖（含水泥路面修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 240.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_230",
    "name": "接地线（电阻≤4Ω，导电良好，工作接地）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_231",
    "name": "普通土地开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_232",
    "name": "普通水泥/砖路面开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_233",
    "name": "超30米电缆敷设 YJV 3*10mm²（含管及人工）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_234",
    "name": "超30米电缆敷设 YJV 3*6mm²（含PVC/镀锌管及人工）",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 45.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_235",
    "name": "铺砖庭院开挖含修复（复合石料地面）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_236",
    "name": "铺砖庭院开挖含修复（花岗岩/高贵资砖地面）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 240.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_237",
    "name": "高空作业费（离地≥5米，按线缆长度计）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_357",
    "name": "50*50mm*1.2mm桥架",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_358",
    "name": "ZR-YJV3*10mm²电缆、镀锌管或PVC管、人工及四年质保",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_359",
    "name": "ZR-YJV3*16mm²电缆、镀锌管或PVC管、人工及四年质保",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 74.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_360",
    "name": "ZR-YJV3*6mm²电缆、镀锌管或PVC管、人工及四年质保",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 45.0,
    "brand": "理想",
    "freeQuota": 30,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_361",
    "name": "充电桩保护箱立柱（含安装）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_362",
    "name": "充电桩枪头锁材料及安装（机械密码锁）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_363",
    "name": "墙体开孔φ32（砖、混凝土墙体）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_364",
    "name": "德力西220V单相有功功率电度表（DDS606 10(40)A）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_365",
    "name": "接地极（φ8圆钢或截面大于100mm²角钢）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_366",
    "name": "普通土质路面土方开挖及修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_367",
    "name": "水泥、沥青、地砖路面开挖及水泥修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_368",
    "name": "理想专属定制充电桩保护箱",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_369",
    "name": "电度表箱（用于单独安装电度表场景，符合防护标准）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_370",
    "name": "超过5米以上高空作业（最高1000元封顶）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "理想",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
