import type { Material } from "../types/material"

export const addonMaterials_batch5Part2: Material[] = [
  {
    "id": "addon_166",
    "name": "充电桩水泥基础（>=350*350*350mm，含预埋螺栓）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_167",
    "name": "充电桩立柱/保护箱/灭火器等安装费（逐个）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_168",
    "name": "充电桩立柱（高度>1.5m冷轧钢，含安装）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_169",
    "name": "单相220V普通电表（含表箱及安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_170",
    "name": "吊筋敷设（含材料及人工）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_171",
    "name": "墙体开孔（非承重墙，孔径32mm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_172",
    "name": "接地极（08圆钢或角钢埋深>1米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_173",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_174",
    "name": "桥架安装（规格50*50mm）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_175",
    "name": "水泥/地砖/柏油路等硬质路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_176",
    "name": "特殊安装地点服务费（景区/岛屿等）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_177",
    "name": "线缆拆除（不含墙面复原）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_178",
    "name": "线缆敷设 ZC-YJV-3*10mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_179",
    "name": "线缆敷设 ZC-YJV-3*16mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_180",
    "name": "线缆敷设 ZC-YJV-3*6mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_181",
    "name": "线缆敷设 ZC-YJV-5*10mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_182",
    "name": "线缆敷设 ZC-YJV-5*16mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_183",
    "name": "线缆敷设 ZC-YJV-5*6mm²（含套管辅材人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_184",
    "name": "高空作业（电缆敷设高度超过5米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "小米",
    "freeQuota": 0,
    "source": "addon"
  }
]
