import { Material } from '../types/material'

export const addonMaterials_batch9: Material[] = [
  {
    "id": "addon_371",
    "name": "一体式保护箱+立柱 7kW",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 550.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_372",
    "name": "上门检测费（质保外/人为损坏）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_373",
    "name": "代办电力报装（其他地区）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_374",
    "name": "代办电力报装（北京）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 600.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_375",
    "name": "充电桩保护盒 7kW",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_376",
    "name": "充电桩移机",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_377",
    "name": "其他材料（膨胀螺丝/尼龙膨胀/铜鼻子等）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 0.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_378",
    "name": "打吊丝",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_379",
    "name": "打地极",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_380",
    "name": "打墙洞/穿墙孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_381",
    "name": "普通土地开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 30.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_382",
    "name": "普通水泥/砖路面开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 90.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_383",
    "name": "桥架及安装 50*50mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_384",
    "name": "沥青路面开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_385",
    "name": "混凝土基础浇筑 400*350*350",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_386",
    "name": "混凝土基础浇筑 600*440*370",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_387",
    "name": "电表 40A单相",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "METER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_388",
    "name": "电表箱 PZ30",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_389",
    "name": "空气开关 220V 40A 2P",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_390",
    "name": "空气开关 220V 40A 2P带漏保",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 85.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_391",
    "name": "空气开关 4P40A带漏保",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_392",
    "name": "空气开关 4P40A带漏保（升级款）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_393",
    "name": "立柱（普通款）7kW",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_394",
    "name": "立柱（直流款）20kW",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 650.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_395",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_396",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 70.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_397",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "空灵吉利",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_398",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 75.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_399",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 90.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_400",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*6mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_401",
    "name": "高空作业费（5米及以上）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
