import type { Material } from "../types/material"

export const addonMaterials_batch9Part1: Material[] = [
  {
    "id": "addon_371",
    "name": "一体式保护箱+立柱 7kW",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 550.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_372",
    "name": "上门检测费（质保外/人为损坏）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_373",
    "name": "代办电力报装（其他地区）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_374",
    "name": "代办电力报装（北京）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_375",
    "name": "充电桩保护盒 7kW",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_376",
    "name": "充电桩移机",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_377",
    "name": "其他材料（膨胀螺丝/尼龙膨胀/铜鼻子等）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_378",
    "name": "打吊丝",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_379",
    "name": "打地极",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_380",
    "name": "打墙洞/穿墙孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_381",
    "name": "普通土地开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_382",
    "name": "普通水泥/砖路面开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_383",
    "name": "桥架及安装 50*50mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_384",
    "name": "沥青路面开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_385",
    "name": "混凝土基础浇筑 400*350*350",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_386",
    "name": "混凝土基础浇筑 600*440*370",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  }
]
