import { Material } from '../types/material'

export const addonMaterials_batch3: Material[] = [
  {
    "id": "addon_82",
    "name": "2P断路器（40-63）+防水盒+安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_83",
    "name": "4P断路器（40-63）+防水盒+安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 160.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_84",
    "name": "5回路断路器防水盒（2P）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_85",
    "name": "8回路断路器防水盒（4P）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 30.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_86",
    "name": "PVC管升级镀锌管",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_87",
    "name": "专业勘测（图纸+报告）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_88",
    "name": "仅拆旧（拆桩）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 170.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_89",
    "name": "保护箱仅安装人工",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_90",
    "name": "保护箱（室外不锈钢600×500×250）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_91",
    "name": "充电桩立柱（含安装费）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_92",
    "name": "吊筋（含辅材及人工）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_93",
    "name": "土路开挖+修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_94",
    "name": "基础勘测（草图）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_95",
    "name": "安装拆旧（同步拆旧机）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_96",
    "name": "挂桩（单独上门固定）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_97",
    "name": "接地极（打地线1.5米）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_98",
    "name": "断路器安装费",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_99",
    "name": "桥架（50×50×1.2mm含安装）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_100",
    "name": "水泥路开挖+修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_101",
    "name": "沥青混凝土开挖+修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_102",
    "name": "混凝土基座制作（含基坑挖填）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_103",
    "name": "混凝土墙开孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_104",
    "name": "电缆拆除（已敷线路）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_105",
    "name": "电缆敷设（用户自购配件）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 15.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_106",
    "name": "砖墙开孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_107",
    "name": "空跑（无效上门）",
    "unit": "单",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_108",
    "name": "立柱安装（不含立柱/基座）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_109",
    "name": "线缆敷设 ZC-YJV-3×10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_110",
    "name": "线缆敷设 ZC-YJV-3×16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_111",
    "name": "线缆敷设 ZC-YJV-3×6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "公牛",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_112",
    "name": "线缆敷设 ZC-YJV-5×10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_113",
    "name": "线缆敷设 ZC-YJV-5×16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 95.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_114",
    "name": "线缆敷设 ZC-YJV-5×6mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_115",
    "name": "草坪砖/镶草砖路面开挖",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_116",
    "name": "高空作业费（>5米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "公牛",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
