import type { Material } from "../types/material"

export const addonMaterials_batch7Part2: Material[] = [
  {
    "id": "addon_311",
    "name": "套包外线缆敷设 ZC-YJV-3*16mm²（含线缆、套管、辅材、人工及2年质保）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_312",
    "name": "套包外线缆敷设 ZC-YJV-3*6mm²（含线缆、套管、辅材、人工及2年质保）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_313",
    "name": "安装服务套包（不含桩）（提供30米以内线缆敷设，含材料30米ZC-YJV-3*6mm²线缆、套管、2P漏保、地极等辅材、人工及安装工程2年质保）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 1350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_314",
    "name": "安装桥架（桥架规格50*50mm*1.2mm，含材料及人工费）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_315",
    "name": "安装立柱人工费（客户提供立柱，不含水泥基础）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_316",
    "name": "枪线升级（套包内充电枪线长度升级，升至7米延长线含材料及人工费）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 550.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_317",
    "name": "特殊安装地点服务费（安装场景涉及特殊安装地点，如景区、岛屿等涉及景点门票或船票时）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_318",
    "name": "电表（德力西DDS606 10(40)A220V单相功率电度表、电表箱，含材料及人工费）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 280.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_319",
    "name": "登高工具租赁（登高工具租赁及运输费用，如脚手架、人字梯等登高工具）",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_320",
    "name": "自布线压接端子（对软铜线、铝线进行压接端子，免费为客户压接端子）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_321",
    "name": "路面开挖及恢复（普通土路）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_322",
    "name": "路面开挖及恢复（柏油路面开挖及恢复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_323",
    "name": "路面开挖及恢复（硬质路面：水泥、地砖、花砖等硬质路面开挖及恢复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_324",
    "name": "额外上门服务（客户原因二次勘测、安装完成后枪线升级、保外维修等）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 140.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_325",
    "name": "额外埋入地极（Ø8圆钢或截面>100mm²角钢，埋深>1米，适用于质保期外维修、移桩场景）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_326",
    "name": "高空作业（线缆敷设作业高度≥5米，按线缆长度收费）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  }
]
