import { Material } from '../types/material'

export const addonMaterials_batch7: Material[] = [
  {
    "id": "addon_294",
    "name": "专业开孔（墙体开孔孔径≤32mm，墙体厚度>40cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_295",
    "name": "专业开孔（墙体开孔孔径≤32mm，墙体厚度≤40cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_296",
    "name": "保护箱安装人工费（客户提供保护箱）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_297",
    "name": "充电桩保护箱（保护箱规格：600*500*250mm，厚度≥0.8mm，材质：冷轧钢）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_298",
    "name": "充电桩桩体拆除（仅含充电桩桩体拆除，适用于维修、移桩场景）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_299",
    "name": "充电桩桩体挂桩（仅含充电桩桩体挂桩及调试，适用维修、移桩场景）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_300",
    "name": "充电桩水泥基础（浇筑充电桩立柱水泥墩，≥300*200*200mm，含预埋螺栓）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_301",
    "name": "充电桩立柱（立柱规格：高度≥1.5m，材质：冷轧钢）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_302",
    "name": "充电桩线缆拆除（仅含线缆、套管等其他辅材拆除，适用于维修、移桩场景）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_303",
    "name": "充电桩线缆敷设（安装敷设原有线缆，含辅材及人工费，适用维修、移桩场景）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 18.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_304",
    "name": "单相漏电保护器（移桩后新地址安装/质保期外维修需更换漏电保护器）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_305",
    "name": "单相空气开关（安装正泰或德力西2P空气开关25A/40A）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_306",
    "name": "吊丝固定（适用于室外架空线缆固定，仅包含吊丝、辅材及人工安装费用）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_307",
    "name": "吊筋固定（适用于地下小区车库架空线管固定，仅包含吊筋、辅材及人工安装费用）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_308",
    "name": "套包内线缆升级 3*6mm²升至3*10mm²",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_309",
    "name": "套包内线缆升级 3*6mm²升至3*16mm²",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 600.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_310",
    "name": "套包外线缆敷设 ZC-YJV-3*10mm²（含线缆、套管、辅材、人工及2年质保）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_311",
    "name": "套包外线缆敷设 ZC-YJV-3*16mm²（含线缆、套管、辅材、人工及2年质保）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_312",
    "name": "套包外线缆敷设 ZC-YJV-3*6mm²（含线缆、套管、辅材、人工及2年质保）",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 45.0,
    "brand": "比亚迪",
    "freeQuota": 30,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_313",
    "name": "安装服务套包（不含桩）（提供30米以内线缆敷设，含材料30米ZC-YJV-3*6mm²线缆、套管、2P漏保、地极等辅材、人工及安装工程2年质保）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 1350.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_314",
    "name": "安装桥架（桥架规格50*50mm*1.2mm，含材料及人工费）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_315",
    "name": "安装立柱人工费（客户提供立柱，不含水泥基础）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_316",
    "name": "枪线升级（套包内充电枪线长度升级，升至7米延长线含材料及人工费）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 550.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_317",
    "name": "特殊安装地点服务费（安装场景涉及特殊安装地点，如景区、岛屿等涉及景点门票或船票时）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 0.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_318",
    "name": "电表（德力西DDS606 10(40)A220V单相功率电度表、电表箱，含材料及人工费）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 280.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_319",
    "name": "登高工具租赁（登高工具租赁及运输费用，如脚手架、人字梯等登高工具）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_320",
    "name": "自布线压接端子（对软铜线、铝线进行压接端子，免费为客户压接端子）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 0.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_321",
    "name": "路面开挖及恢复（普通土路）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_322",
    "name": "路面开挖及恢复（柏油路面开挖及恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_323",
    "name": "路面开挖及恢复（硬质路面：水泥、地砖、花砖等硬质路面开挖及恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_324",
    "name": "额外上门服务（客户原因二次勘测、安装完成后枪线升级、保外维修等）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 140.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_325",
    "name": "额外埋入地极（Ø8圆钢或截面>100mm²角钢，埋深>1米，适用于质保期外维修、移桩场景）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_326",
    "name": "高空作业（线缆敷设作业高度≥5米，按线缆长度收费）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "比亚迪",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  }
]
