import type { Material } from "../types/material"

export const addonMaterials_batch10Part1: Material[] = [
  {
    "id": "addon_402",
    "name": "二次勘测费（现场勘测及方案设计）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_403",
    "name": "保护箱安装（客户自购保护箱，仅安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_404",
    "name": "停车限位胶（制作和安装）",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "组",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_405",
    "name": "充电器保护箱（500*600*250mm，含箱体及安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_406",
    "name": "充电桩水泥基础（500*500*200mm）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_407",
    "name": "充电桩立柱（含安装，高度1.3~1.5m）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_408",
    "name": "售后服务费（检查或维修人工及辅料）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_409",
    "name": "套内线缆升级至3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_410",
    "name": "套内线缆升级至3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_411",
    "name": "开沟开槽 A1土路（承重道路）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_412",
    "name": "开沟开槽 A2水泥路（承重道路）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 130.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_413",
    "name": "开沟开槽 A3柏油路（承重道路）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_414",
    "name": "开沟开槽 B1土路/草地（非承重）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_415",
    "name": "开沟开槽 B2水泥路（非承重）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_416",
    "name": "开沟开槽 B3铺砖庭院（非承重）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_417",
    "name": "报装服务费（完全代理报装服务）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 500.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_418",
    "name": "漏电保护开关（2P C40A型漏保更换及安装）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_419",
    "name": "电度表（单相电度表80A及以下）",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 280.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  }
]
