import type { Material } from "../types/material"

export const addonMaterials_batch8Part2: Material[] = [
  {
    "id": "addon_342",
    "name": "充电桩保护箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_343",
    "name": "墙体开孔（孔径Φ32mm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_344",
    "name": "套包内线缆升级规格",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_345",
    "name": "接地极（深埋1.5米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_346",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_347",
    "name": "柏油路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_348",
    "name": "桥架安装50*50mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_349",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_350",
    "name": "电表仅安装人工费（不含电表及表箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_351",
    "name": "立柱及安装（≥1.5m冷轧钢）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_352",
    "name": "立柱水泥基础制作（300*200*200mm）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_353",
    "name": "草坪砖/镶草砖/步道砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_354",
    "name": "裸机和漏保（盒）拆除（不含线路）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_355",
    "name": "额外上门服务",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_356",
    "name": "高空作业（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  }
]
