import type { Material } from "../types/material"

export const addonMaterials_batch3Part2: Material[] = [
  {
    "id": "addon_100",
    "name": "水泥路开挖+修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_101",
    "name": "沥青混凝土开挖+修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_102",
    "name": "混凝土基座制作（含基坑挖填）",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_103",
    "name": "混凝土墙开孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_104",
    "name": "电缆拆除（已敷线路）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_105",
    "name": "电缆敷设（用户自购配件）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_106",
    "name": "砖墙开孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_107",
    "name": "空跑（无效上门）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "单",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_108",
    "name": "立柱安装（不含立柱/基座）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_109",
    "name": "线缆敷设 ZC-YJV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_110",
    "name": "线缆敷设 ZC-YJV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_111",
    "name": "线缆敷设 ZC-YJV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_112",
    "name": "线缆敷设 ZC-YJV-5*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_113",
    "name": "线缆敷设 ZC-YJV-5*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 95.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_114",
    "name": "线缆敷设 ZC-YJV-5*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_115",
    "name": "草坪砖/镶草砖路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_116",
    "name": "高空作业费（>5米）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  }
]
