import { Material } from '../types/material'

export const addonMaterials_batch6: Material[] = [
  {
    "id": "addon_185",
    "name": "上门服务费 偏远地区",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "公里",
    "costPrice": 0,
    "settlementPrice": 1.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_186",
    "name": "上门服务费 其他三四线城市",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_187",
    "name": "上门服务费 省会/一二线",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_188",
    "name": "代理电力报装",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_189",
    "name": "充电桩立柱(含安装)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_190",
    "name": "墙面开槽及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_191",
    "name": "套包内电缆升级",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_192",
    "name": "拆移桩服务 原线缆拆除",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_193",
    "name": "拆移桩服务 原设备拆除",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_194",
    "name": "拆移桩服务 新设备安装",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_195",
    "name": "拆移桩服务 线缆敷设(旧电缆)",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_196",
    "name": "接地极",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_197",
    "name": "断路器保护盒 5/6位",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_198",
    "name": "断路器保护盒 8/12位",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_199",
    "name": "漏电断路器 11KW(380V/4P,20A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_200",
    "name": "漏电断路器 21KW(380V/4P,40A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_201",
    "name": "漏电断路器 7KW(220V/2P,40A/30mA/A型,良信/正泰)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_202",
    "name": "电源点空开(63A)",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_203",
    "name": "电缆敷设(三项) YJV-5*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_204",
    "name": "电缆敷设(三项) YJV-5*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_205",
    "name": "电缆敷设(三项) YJV-5*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_206",
    "name": "电缆敷设(单项) YJV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_207",
    "name": "电缆敷设(单项) YJV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_208",
    "name": "电缆敷设(单项) YJV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_209",
    "name": "电缆桥架(100*50mm)",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_210",
    "name": "电表 220V 10(40)A单项",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_211",
    "name": "电表 380V 10(40)A三项",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_212",
    "name": "电表箱(PZ40)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_213",
    "name": "穿墙打孔 40-60cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_214",
    "name": "穿墙打孔 60-80cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_215",
    "name": "穿墙打孔 ≤40cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_216",
    "name": "立柱安装(客户自备立柱)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_217",
    "name": "立柱水泥基础(400*300*400mm)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_218",
    "name": "路面开槽及恢复 土路/草地",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_219",
    "name": "路面开槽及恢复 水泥路",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_220",
    "name": "路面开槽及恢复 铺砖庭院",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_221",
    "name": "防雨防盗箱(600*500*250mm,含安装)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_222",
    "name": "防雨防盗箱(仅安装)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_223",
    "name": "高空作业(>5米)",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  }
]
