import type { Material } from "../types/material"

export const addonMaterials_batch13Part1: Material[] = [
  {
    "id": "addon_458",
    "name": "充电桩混凝土基础",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_459",
    "name": "充电桩防护箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_460",
    "name": "充电桩防护箱安装（客户提供）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_461",
    "name": "单相电表",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_462",
    "name": "单相电表（含表箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 145.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_463",
    "name": "墙体开孔（混凝土）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_464",
    "name": "墙体开孔（砖墙）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_465",
    "name": "断路器及安装 2P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_466",
    "name": "断路器及安装 4P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_467",
    "name": "桥架及安装 50*50mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_468",
    "name": "水泥路路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_469",
    "name": "沥青路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_470",
    "name": "泥土路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_471",
    "name": "电缆升级 3*10mm²（超100米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_472",
    "name": "电缆升级 3*16mm²（超150米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_473",
    "name": "电缆及敷设 ZR-YJV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_474",
    "name": "电缆及敷设 ZR-YJV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_475",
    "name": "电缆及敷设 ZR-YJV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_476",
    "name": "立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 192.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_477",
    "name": "立柱安装（客户提供）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_478",
    "name": "铺砖+泥土开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_479",
    "name": "额外上门（超两次）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  }
]
