import type { Material } from "../types/material"

export const addonMaterials_batch1Part1: Material[] = [
  {
    "id": "addon_1",
    "name": "0米套包拆除旧充电桩桩体",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_2",
    "name": "40A三相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_3",
    "name": "40A单相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_4",
    "name": "ZC-YJV 3*6mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_5",
    "name": "ZR-YJV 3*10mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_6",
    "name": "ZR-YJV 3*16mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_7",
    "name": "ZR-YJV 5*10mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_8",
    "name": "ZR-YJV 5*16mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 95.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_9",
    "name": "ZR-YJV 5*6mm²国标线缆敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_10",
    "name": "仅保护箱安装人工费（用户提供）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_11",
    "name": "仅原安装线路拆除（不含复原）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_12",
    "name": "仅电表安装人工费（不含电表及表箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_13",
    "name": "仅线缆敷设人工费（用户自购线缆）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_14",
    "name": "充电桩保护箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_15",
    "name": "吊筋（辅材及人工安装）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_16",
    "name": "墙面开水钻孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_17",
    "name": "套包内2P漏保升级施耐德/ABB/西门子",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_18",
    "name": "套包内4P漏保升级施耐德/ABB/西门子",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_19",
    "name": "套包内线缆升级一个规格",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  }
]
