import type { Material } from "../types/material"

export const addonMaterials_batch9Part2: Material[] = [
  {
    "id": "addon_387",
    "name": "电表 40A单相",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_388",
    "name": "电表箱 PZ30",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_389",
    "name": "空气开关 220V 40A 2P",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_390",
    "name": "空气开关 220V 40A 2P带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 85.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_391",
    "name": "空气开关 4P40A带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_392",
    "name": "空气开关 4P40A带漏保（升级款）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_393",
    "name": "立柱（普通款）7kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_394",
    "name": "立柱（直流款）20kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 650.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_395",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_396",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_397",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_398",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_399",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_400",
    "name": "线缆敷设 ZR/ZC/ZB/ZA-YJV-5*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_401",
    "name": "高空作业费（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵吉利",
    "freeQuota": 0,
    "source": "addon"
  }
]
