import { Material } from '../types/material'

export const addonMaterials_batch2: Material[] = [
  {
    "id": "addon_38",
    "name": "不锈钢防雨开关箱箱体（户外型）及安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_39",
    "name": "墙面开槽及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_40",
    "name": "墙面穿孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_41",
    "name": "套餐升级费用 3*6升3*10（80-150米）",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_42",
    "name": "套餐升级费用 3*6升3*16（150米+）",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 750.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_43",
    "name": "家充桩保护箱安装（不含箱体）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_44",
    "name": "家充桩保护箱箱体（户外型）及安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 600.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_45",
    "name": "家充桩立柱及安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_46",
    "name": "家充桩立柱安装（不含立柱）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_47",
    "name": "接地极",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_48",
    "name": "柏油路面开槽及修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_49",
    "name": "桥架及安装 50*50*1.2mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_50",
    "name": "水泥路面开槽及修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 220.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_51",
    "name": "浪涌保护器",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "SURGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_52",
    "name": "混凝土基础浇筑",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_53",
    "name": "漏电保护开关（进口品牌）2P 220V 40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 220.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_54",
    "name": "电力报装费用（北京）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 800.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_55",
    "name": "草坪/土地开槽及修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_56",
    "name": "超基础套包线缆费（3*10mm²）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_57",
    "name": "超基础套包线缆费（3*16mm²）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 75.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_58",
    "name": "超基础套包线缆费（3*6mm²）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 45.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_59",
    "name": "铺砖路面开槽及修复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_60",
    "name": "高空作业",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "上汽通用",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_61",
    "name": "PVC管升级镀锌管",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_62",
    "name": "二次勘测上门服务费",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_63",
    "name": "保护箱安装（用户提供）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_64",
    "name": "充电桩保护外箱（不锈钢）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_65",
    "name": "充电桩立柱",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_66",
    "name": "充电桩立柱水泥墩",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_67",
    "name": "吊筋丝杆",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_68",
    "name": "墙面线管开槽（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_69",
    "name": "墙面钻孔（厚度<40CM）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_70",
    "name": "墙面钻孔（厚度>40CM）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_71",
    "name": "断路器（空气开关）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_72",
    "name": "普通土路地面开挖（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_73",
    "name": "桥架 50*50*1.2mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_74",
    "name": "水泥/地砖地面开挖（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_75",
    "name": "立柱安装（用户提供）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_76",
    "name": "线缆升级 YJV-0.6/1kV-3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_77",
    "name": "线缆升级 YJV-0.6/1kV-3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_78",
    "name": "线缆敷设 YJV-0.6/1kV-3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "五菱",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_79",
    "name": "远程服务费（超出30公里）",
    "unit": "公里",
    "costPrice": null,
    "customerPrice": 4.0,
    "brand": "五菱",
    "freeQuota": 30,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_80",
    "name": "预埋接地线（有接地极免费）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_81",
    "name": "高空作业费（4米及以上）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "五菱",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
