import type { Material } from "../types/material"

export const addonMaterials_batch13Part2: Material[] = [
  {
    "id": "addon_480",
    "name": "高空作业（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 32.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "长城",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_437",
    "name": "PVC管升级镀锌管",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_438",
    "name": "二次勘测上门服务费",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_439",
    "name": "保护箱安装（客户提供）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_440",
    "name": "充电桩保护外箱（不锈钢）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_441",
    "name": "充电桩立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_442",
    "name": "吊筋特殊环境（丝杆）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_443",
    "name": "墙面线管开槽（含恢复）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_444",
    "name": "墙面钻孔（厚度<40CM）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_445",
    "name": "墙面钻孔（厚度>40CM）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_446",
    "name": "断路器（空气开关）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_447",
    "name": "普通土路地面线管开挖（含恢复）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_448",
    "name": "桥架 50mm*50mm*1.2mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_449",
    "name": "水泥/地砖地面线管开挖（含恢复）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_450",
    "name": "浇筑充电桩立柱水泥墩",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_451",
    "name": "立柱安装（客户提供）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_452",
    "name": "线缆升级 3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_453",
    "name": "线缆升级 3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_454",
    "name": "线缆敷设 YJV-0.6/1kV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_455",
    "name": "远程服务费（超出30公里）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "公里",
    "costPrice": 0,
    "settlementPrice": 4.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_456",
    "name": "预埋接地线（有接地极免费）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_457",
    "name": "高空作业费（4米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "西安领充",
    "freeQuota": 0,
    "source": "addon"
  }
]
