import type { Material } from "../types/material"

export const addonMaterials_batch1Part2: Material[] = [
  {
    "id": "addon_20",
    "name": "套包外2P漏保开关（施耐德/ABB/西门子）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_21",
    "name": "套包外2P漏保开关（正泰/德力西）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_22",
    "name": "套包外4P漏保开关（施耐德/ABB/西门子）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 260.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_23",
    "name": "套包外4P漏保开关（正泰/德力西）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_24",
    "name": "接地极（深埋1.5米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_25",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_26",
    "name": "普通墙体钻孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_27",
    "name": "未套管优惠减免",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": -5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_28",
    "name": "柏油路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_29",
    "name": "桥架安装（50*50mm）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_30",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_31",
    "name": "用户自行提供立柱安装（普通）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_32",
    "name": "用户自行提供立柱安装（电动伸缩）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_33",
    "name": "立柱及安装（冷轧钢≥1.5m）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_34",
    "name": "立柱水泥基础制作",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_35",
    "name": "草坪砖/渗水砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_36",
    "name": "额外上门/空跑费",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_37",
    "name": "高空作业（线缆高度超5米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "source": "addon"
  }
]
