import type { Material } from "../types/material"

export const addonMaterials_batch12Part2: Material[] = [
  {
    "id": "addon_561",
    "name": "空气开关 220V 40A 2P带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 85.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_562",
    "name": "空气开关 4P40A带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_563",
    "name": "空气开关 4P40A带漏保（升级款）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_564",
    "name": "立柱（普通款）7kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_565",
    "name": "立柱（直流款）20kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 650.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_566",
    "name": "线缆敷设 ZR-YJV 3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_567",
    "name": "线缆敷设 ZR-YJV 3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_568",
    "name": "线缆敷设 ZR-YJV 3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_569",
    "name": "线缆敷设 ZR-YJV 5*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_570",
    "name": "线缆敷设 ZR-YJV 5*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_571",
    "name": "线缆敷设 ZR-YJV 5*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_572",
    "name": "高空作业费（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_481",
    "name": "保护箱安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_482",
    "name": "勘测（两次以上）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 1,
    "source": "addon"
  },
  {
    "id": "addon_483",
    "name": "墙体开孔>40mm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_484",
    "name": "墙体开孔≤40mm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_485",
    "name": "充电桩拆除",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_486",
    "name": "充电桩挂装",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_487",
    "name": "接地极及安装",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  }
]
