import type { Material } from "../types/material"

export const addonMaterials_batch8Part1: Material[] = [
  {
    "id": "addon_327",
    "name": "2P开关（施耐德/ABB/西门子）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_328",
    "name": "2P开关（正泰/德力西）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_329",
    "name": "40A三相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_330",
    "name": "40A单相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_331",
    "name": "4P开关（施耐德/ABB/西门子）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 220.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_332",
    "name": "4P开关（正泰/德力西）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_333",
    "name": "ZR-YJV 3*10mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_334",
    "name": "ZR-YJV 3*16mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_335",
    "name": "ZR-YJV 3*6mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_336",
    "name": "ZR-YJV 5*10mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_337",
    "name": "ZR-YJV 5*16mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_338",
    "name": "ZR-YJV 5*6mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_339",
    "name": "仅原安装线路拆除（不含墙面复原）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_340",
    "name": "仅线缆敷设人工费（用户自购线缆）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_341",
    "name": "保护箱仅安装人工费（不含保护箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  }
]
