import type { Material } from "../types/material"

export const addonMaterials_batch3Part1: Material[] = [
  {
    "id": "addon_82",
    "name": "2P断路器（40-63）+防水盒+安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_83",
    "name": "4P断路器（40-63）+防水盒+安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_84",
    "name": "5回路断路器防水盒（2P）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_85",
    "name": "8回路断路器防水盒（4P）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_86",
    "name": "PVC管升级镀锌管",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_87",
    "name": "专业勘测（图纸+报告）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_88",
    "name": "仅拆旧（拆桩）",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 170.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_89",
    "name": "保护箱仅安装人工",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_90",
    "name": "保护箱（室外不锈钢600×500×250）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_91",
    "name": "充电桩立柱（含安装费）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_92",
    "name": "吊筋（含辅材及人工）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_93",
    "name": "土路开挖+修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_94",
    "name": "基础勘测（草图）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_95",
    "name": "安装拆旧（同步拆旧机）",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_96",
    "name": "挂桩（单独上门固定）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_97",
    "name": "接地极（打地线1.5米）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_98",
    "name": "断路器安装费",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_99",
    "name": "桥架（50×50×1.2mm含安装）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "公牛",
    "freeQuota": 0,
    "source": "addon"
  }
]
