import type { Material } from "../types/material"

export const addonMaterials_batch2Part1: Material[] = [
  {
    "id": "addon_38",
    "name": "不锈钢防雨开关箱箱体（户外型）及安装",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_39",
    "name": "墙面开槽及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_40",
    "name": "墙面穿孔",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_41",
    "name": "套餐升级费用 3*6升3*10（80-150米）",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_42",
    "name": "套餐升级费用 3*6升3*16（150米+）",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 750.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_43",
    "name": "家充桩保护箱安装（不含箱体）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_44",
    "name": "家充桩保护箱箱体（户外型）及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_45",
    "name": "家充桩立柱及安装",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_46",
    "name": "家充桩立柱安装（不含立柱）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_47",
    "name": "接地极",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_48",
    "name": "柏油路面开槽及修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_49",
    "name": "桥架及安装 50*50*1.2mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_50",
    "name": "水泥路面开槽及修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 220.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_51",
    "name": "浪涌保护器",
    "category": "浪涌",
    "categoryCode": "SURGE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_52",
    "name": "混凝土基础浇筑",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_53",
    "name": "漏电保护开关（进口品牌）2P 220V 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 220.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_54",
    "name": "电力报装费用（北京）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 800.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_55",
    "name": "草坪/土地开槽及修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_56",
    "name": "超基础套包线缆费（3*10mm²）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_57",
    "name": "超基础套包线缆费（3*16mm²）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_58",
    "name": "超基础套包线缆费（3*6mm²）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_59",
    "name": "铺砖路面开槽及修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  }
]
