import type { Material } from "../types/material"

export const addonMaterials_batch12Part3: Material[] = [
  {
    "id": "addon_488",
    "name": "断路器2P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_489",
    "name": "断路器4P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 140.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_490",
    "name": "桥架50*50*1.0mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_491",
    "name": "水泥路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_492",
    "name": "沥青路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_493",
    "name": "泥土路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_494",
    "name": "混凝土基础浇筑",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_495",
    "name": "漏保40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 260.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_496",
    "name": "电缆ZR-YJV-3*6",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_497",
    "name": "电缆ZR-YJV-5*4",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_498",
    "name": "线缆升级",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_499",
    "name": "充电桩立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_500",
    "name": "管线拆除",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_501",
    "name": "管线敷设",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 18.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_502",
    "name": "线管φ32mm",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 7.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_503",
    "name": "维修人工",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_504",
    "name": "铺砖路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_505",
    "name": "充电桩保护箱",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_506",
    "name": "高空作业",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  }
]
