import { Material } from '../types/material'

export const addonMaterials_batch11: Material[] = [
  {
    "id": "addon_238",
    "name": "保护箱安装人工费（客户提供）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_239",
    "name": "充电桩保护箱（600*500*250mm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_240",
    "name": "充电桩桩体拆除",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_241",
    "name": "充电桩桩体挂桩",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_242",
    "name": "充电桩立柱（冷轧钢≥1.5m）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_243",
    "name": "充电桩线缆拆除",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 15.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_244",
    "name": "单相电表和电表箱及安装",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 280.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_245",
    "name": "吊筋敷设（含材料及人工）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_246",
    "name": "墙体开孔>40cm",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_247",
    "name": "墙体开孔≤40cm",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_248",
    "name": "套包内线缆升级3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_249",
    "name": "套包内线缆升级3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_250",
    "name": "套包外电缆敷设3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_251",
    "name": "套包外电缆敷设3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_252",
    "name": "套包外电缆敷设3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 45.0,
    "brand": "捷途",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_253",
    "name": "安装服务套包（30米线缆敷设）",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 1350.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_254",
    "name": "接地极（Ø8圆钢埋深>1米）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_255",
    "name": "断路器安装（正泰/德力西40A）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_256",
    "name": "普通土路开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_257",
    "name": "柏油路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_258",
    "name": "桥架安装50*50*1.2mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_259",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_260",
    "name": "移桩线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 25.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_261",
    "name": "立柱安装人工费（客户提供）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_262",
    "name": "立柱水泥基础（≥300*200*200mm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_263",
    "name": "额外上门服务",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_264",
    "name": "高空作业（>5米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "捷途",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_265",
    "name": "充电桩立柱混凝土基础浇筑",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_266",
    "name": "吊筋敷设",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_267",
    "name": "墙面开槽及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_268",
    "name": "套管升级 镀锌管JDG25",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 7.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_269",
    "name": "套管升级 镀锌管JDG32",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 13.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_270",
    "name": "套餐内升级电缆 3*6升3*10",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_271",
    "name": "套餐内升级电缆 5*6升5*10",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 15.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_272",
    "name": "安装开孔 ≤35mm",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_273",
    "name": "工作接地",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_274",
    "name": "承重路面 沥青路/柏油路",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_275",
    "name": "更换漏保 三相20A/40A AC型",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_276",
    "name": "更换漏保 单相20A/40A AC型",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_277",
    "name": "漏电保护器 三相11KW AC型",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_278",
    "name": "漏电保护器 三相21KW AC型",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_279",
    "name": "漏电保护器 单相7KW AC型",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 70.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_280",
    "name": "特殊安装地点费用",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 0.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_281",
    "name": "电缆及套管 3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_282",
    "name": "电缆及套管 3*16mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 65.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_283",
    "name": "电缆及套管 3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_284",
    "name": "电缆及套管 5*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_285",
    "name": "电缆及套管 5*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 115.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_286",
    "name": "电缆及套管 5*6mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_287",
    "name": "立柱/保护箱安装",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_288",
    "name": "路面开挖及恢复 土路",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_289",
    "name": "路面开挖及恢复 承重水泥路面",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_290",
    "name": "路面开挖及恢复 普通水泥路面",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_291",
    "name": "路面开挖及恢复 普通砖面",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_292",
    "name": "镀锌桥架架设 CT50*50*1.0",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 45.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_293",
    "name": "高空作业",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "支付宝598",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
