import { Material } from '../types/material'

export const addonMaterials_batch4: Material[] = [
  {
    "id": "addon_117",
    "name": "代为电力报装（劳务+交通）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_118",
    "name": "保护箱仅安装人工费",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_119",
    "name": "充电柱线缆拆除（管线及材料）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_120",
    "name": "充电桩保护箱（600*500*250mm冷轧钢≥0.8mm）及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_121",
    "name": "充电桩桩体拆除（仅桩体）",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_122",
    "name": "单相电表（220V）及安装",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_123",
    "name": "地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_124",
    "name": "墙体开孔（孔径Φ25mm，墙体>40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_125",
    "name": "墙体开孔（孔径Φ25mm，墙体≤40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_126",
    "name": "套包内线缆升级至3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_127",
    "name": "套包内线缆升级至3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_128",
    "name": "套包外电缆敷设 ZC-YJV 3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_129",
    "name": "套包外电缆敷设 ZC-YJV 3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_130",
    "name": "套包外电缆敷设 ZC-YJV 3*6mm²（含辅材人工2年质保）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_131",
    "name": "接地极（镀锌材质长60cm含安装人工）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_132",
    "name": "断路器安装（正泰空气开关25A/40A含材料人工）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_133",
    "name": "普通土路开挖及恢复（0.3m*0.4m）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_134",
    "name": "柏油路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_135",
    "name": "桥架安装（含材料及人工）50*50mm*1.2mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_136",
    "name": "水泥路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_137",
    "name": "特殊安装地点服务费（景区/岛屿等）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_138",
    "name": "电表箱及安装（正泰40A）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_139",
    "name": "移桩线缆敷设（含人工辅材2年质保）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_140",
    "name": "立柱基础浇筑（≥300*200*200mm含预埋螺栓）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_141",
    "name": "立柱安装服务（不含水泥基础）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_142",
    "name": "立柱材料费（冷轧钢）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_143",
    "name": "远程上门服务（单程>50km超出部分）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "公里",
    "costPrice": 0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_144",
    "name": "额外上门服务（客户原因）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_145",
    "name": "高空作业（>5米按线缆长度收费）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  }
]
