import { Material } from '../types/material'

export const addonMaterials_batch1: Material[] = [
  {
    "id": "addon_1",
    "name": "0米套包拆除旧充电桩桩体",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_2",
    "name": "40A三相电度表和电表箱及安装",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_3",
    "name": "40A单相电度表和电表箱及安装",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_4",
    "name": "ZC-YJV 3*6mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "万帮星星充电",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_5",
    "name": "ZR-YJV 3*10mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_6",
    "name": "ZR-YJV 3*16mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_7",
    "name": "ZR-YJV 5*10mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_8",
    "name": "ZR-YJV 5*16mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 95.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_9",
    "name": "ZR-YJV 5*6mm²国标线缆敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_10",
    "name": "仅保护箱安装人工费（用户提供）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_11",
    "name": "仅原安装线路拆除（不含复原）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 5.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_12",
    "name": "仅电表安装人工费（不含电表及表箱）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_13",
    "name": "仅线缆敷设人工费（用户自购线缆）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 15.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_14",
    "name": "充电桩保护箱及安装",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_15",
    "name": "吊筋（辅材及人工安装）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_16",
    "name": "墙面开水钻孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_17",
    "name": "套包内2P漏保升级施耐德/ABB/西门子",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_18",
    "name": "套包内4P漏保升级施耐德/ABB/西门子",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_19",
    "name": "套包内线缆升级一个规格",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_20",
    "name": "套包外2P漏保开关（施耐德/ABB/西门子）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 160.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_21",
    "name": "套包外2P漏保开关（正泰/德力西）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_22",
    "name": "套包外4P漏保开关（施耐德/ABB/西门子）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 260.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_23",
    "name": "套包外4P漏保开关（正泰/德力西）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_24",
    "name": "接地极（深埋1.5米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_25",
    "name": "普通土路开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_26",
    "name": "普通墙体钻孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_27",
    "name": "未套管优惠减免",
    "unit": "米",
    "costPrice": null,
    "customerPrice": -5.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_28",
    "name": "柏油路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_29",
    "name": "桥架安装（50*50mm）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_30",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_31",
    "name": "用户自行提供立柱安装（普通）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_32",
    "name": "用户自行提供立柱安装（电动伸缩）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_33",
    "name": "立柱及安装（冷轧钢≥1.5m）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_34",
    "name": "立柱水泥基础制作",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_35",
    "name": "草坪砖/渗水砖路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_36",
    "name": "额外上门/空跑费",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_37",
    "name": "高空作业（线缆高度超5米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "万帮星星充电",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  }
]
