import type { Material } from "../types/material"

export const addonMaterials_batch11Part3: Material[] = [
  {
    "id": "addon_276",
    "name": "更换漏保 单相20A/40A AC型",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_277",
    "name": "漏电保护器 三相11KW AC型",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_278",
    "name": "漏电保护器 三相21KW AC型",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_279",
    "name": "漏电保护器 单相7KW AC型",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_280",
    "name": "特殊安装地点费用",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_281",
    "name": "电缆及套管 3*10mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_282",
    "name": "电缆及套管 3*16mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_283",
    "name": "电缆及套管 3*6mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_284",
    "name": "电缆及套管 5*10mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_285",
    "name": "电缆及套管 5*16mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 115.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_286",
    "name": "电缆及套管 5*6mm²",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_287",
    "name": "立柱/保护箱安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_288",
    "name": "路面开挖及恢复 土路",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_289",
    "name": "路面开挖及恢复 承重水泥路面",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_290",
    "name": "路面开挖及恢复 普通水泥路面",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_291",
    "name": "路面开挖及恢复 普通砖面",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_292",
    "name": "镀锌桥架架设 CT50*50*1.0",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_293",
    "name": "高空作业",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "支付宝598",
    "freeQuota": 0,
    "source": "addon"
  }
]
