import { Material } from '../types/material'

export const addonMaterials_batch10: Material[] = [
  {
    "id": "addon_402",
    "name": "二次勘测费（现场勘测及方案设计）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_403",
    "name": "保护箱安装（客户自购保护箱，仅安装）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_404",
    "name": "停车限位胶（制作和安装）",
    "unit": "组",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_405",
    "name": "充电器保护箱（500*600*250mm，含箱体及安装）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_406",
    "name": "充电桩水泥基础（500*500*200mm）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_407",
    "name": "充电桩立柱（含安装，高度1.3~1.5m）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_408",
    "name": "售后服务费（检查或维修人工及辅料）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_409",
    "name": "套内线缆升级至3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 5.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_410",
    "name": "套内线缆升级至3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_411",
    "name": "开沟开槽 A1土路（承重道路）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_412",
    "name": "开沟开槽 A2水泥路（承重道路）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 130.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_413",
    "name": "开沟开槽 A3柏油路（承重道路）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_414",
    "name": "开沟开槽 B1土路/草地（非承重）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_415",
    "name": "开沟开槽 B2水泥路（非承重）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_416",
    "name": "开沟开槽 B3铺砖庭院（非承重）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_417",
    "name": "报装服务费（完全代理报装服务）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 500.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_418",
    "name": "漏电保护开关（2P C40A型漏保更换及安装）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_419",
    "name": "电度表（单相电度表80A及以下）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 280.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_420",
    "name": "电缆敷设 YJV 3*6mm²（含人工）",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 45.0,
    "brand": "空灵零跑",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_421",
    "name": "电缆敷设 YJV-0.6/1KV 3*10mm²（含人工）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_422",
    "name": "电缆敷设 YJV-0.6/1KV 3*16mm²（含人工）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_423",
    "name": "电缆桥架（布设50mm*100mm）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_424",
    "name": "移桩-充电桩体拆除",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_425",
    "name": "移桩-充电桩体拆除和挂装",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_426",
    "name": "移桩-充电桩体挂装",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_427",
    "name": "移桩-充电桩线缆拆除",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_428",
    "name": "移桩-充电桩线缆敷设（仅适用于维修、移桩场景）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 25.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_429",
    "name": "穿墙打孔（20cm<墙体厚度≤40cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_430",
    "name": "穿墙打孔（40cm<墙体厚度≤60cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_431",
    "name": "穿墙打孔（60cm<墙体厚度≤80cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_432",
    "name": "穿墙打孔（墙体厚度≤20cm）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_433",
    "name": "立柱安装（客户自购立柱，仅安装）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_434",
    "name": "钢结构底座制作及安装（400*330*150mm）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_435",
    "name": "防撞警示柱（制作和安装）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_436",
    "name": "高空架设（电缆敷设5米及以上，1000元封顶）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  }
]
