import type { Material } from "../types/material"

export const addonMaterials_batch4Part1: Material[] = [
  {
    "id": "addon_117",
    "name": "代为电力报装（劳务+交通）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_118",
    "name": "保护箱仅安装人工费",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_119",
    "name": "充电柱线缆拆除（管线及材料）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_120",
    "name": "充电桩保护箱（600*500*250mm冷轧钢≥0.8mm）及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_121",
    "name": "充电桩桩体拆除（仅桩体）",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_122",
    "name": "单相电表（220V）及安装",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_123",
    "name": "地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_124",
    "name": "墙体开孔（孔径Φ25mm，墙体>40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_125",
    "name": "墙体开孔（孔径Φ25mm，墙体≤40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_126",
    "name": "套包内线缆升级至3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_127",
    "name": "套包内线缆升级至3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_128",
    "name": "套包外电缆敷设 ZC-YJV 3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_129",
    "name": "套包外电缆敷设 ZC-YJV 3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_130",
    "name": "套包外电缆敷设 ZC-YJV 3*6mm²（含辅材人工2年质保）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_131",
    "name": "接地极（镀锌材质长60cm含安装人工）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "奇瑞iCAR",
    "freeQuota": 0,
    "source": "addon"
  }
]
