import { Material } from '../types/material'

export const addonMaterials_batch8: Material[] = [
  {
    "id": "addon_327",
    "name": "2P开关（施耐德/ABB/西门子）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 160.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_328",
    "name": "2P开关（正泰/德力西）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_329",
    "name": "40A三相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_330",
    "name": "40A单相电度表和电表箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_331",
    "name": "4P开关（施耐德/ABB/西门子）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 220.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_332",
    "name": "4P开关（正泰/德力西）及人工",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_333",
    "name": "ZR-YJV 3*10mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_334",
    "name": "ZR-YJV 3*16mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_335",
    "name": "ZR-YJV 3*6mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_336",
    "name": "ZR-YJV 5*10mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_337",
    "name": "ZR-YJV 5*16mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_338",
    "name": "ZR-YJV 5*6mm²线缆及敷设",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_339",
    "name": "仅原安装线路拆除（不含墙面复原）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_340",
    "name": "仅线缆敷设人工费（用户自购线缆）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 15.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_341",
    "name": "保护箱仅安装人工费（不含保护箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_342",
    "name": "充电桩保护箱及安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_343",
    "name": "墙体开孔（孔径Φ32mm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_344",
    "name": "套包内线缆升级规格",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_345",
    "name": "接地极（深埋1.5米）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_346",
    "name": "普通土路开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_347",
    "name": "柏油路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_348",
    "name": "桥架安装50*50mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_349",
    "name": "水泥/地砖/花砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_350",
    "name": "电表仅安装人工费（不含电表及表箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_351",
    "name": "立柱及安装（≥1.5m冷轧钢）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_352",
    "name": "立柱水泥基础制作（300*200*200mm）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_353",
    "name": "草坪砖/镶草砖/步道砖路面开挖及恢复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_354",
    "name": "裸机和漏保（盒）拆除（不含线路）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_355",
    "name": "额外上门服务",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_356",
    "name": "高空作业（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "特来电",
    "freeQuota": 0,
    "source": "addon"
  }
]
