import { Material } from '../types/material'

export const addonMaterials_batch13: Material[] = [
  {
    "id": "addon_458",
    "name": "充电桩混凝土基础",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_459",
    "name": "充电桩防护箱及安装",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_460",
    "name": "充电桩防护箱安装（客户提供）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_461",
    "name": "单相电表",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "METER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_462",
    "name": "单相电表（含表箱）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 145.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_463",
    "name": "墙体开孔（混凝土）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_464",
    "name": "墙体开孔（砖墙）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_465",
    "name": "断路器及安装 2P 40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_466",
    "name": "断路器及安装 4P 40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_467",
    "name": "桥架及安装 50*50mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_468",
    "name": "水泥路路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 90.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_469",
    "name": "沥青路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_470",
    "name": "泥土路面开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_471",
    "name": "电缆升级 3*10mm²（超100米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_472",
    "name": "电缆升级 3*16mm²（超150米）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 600.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_473",
    "name": "电缆及敷设 ZR-YJV-3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_474",
    "name": "电缆及敷设 ZR-YJV-3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_475",
    "name": "电缆及敷设 ZR-YJV-3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "长城",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_476",
    "name": "立柱",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 192.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_477",
    "name": "立柱安装（客户提供）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_478",
    "name": "铺砖+泥土开挖及恢复",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_479",
    "name": "额外上门（超两次）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_480",
    "name": "高空作业（5米及以上）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 32.0,
    "brand": "长城",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_437",
    "name": "PVC管升级镀锌管",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_438",
    "name": "二次勘测上门服务费",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_439",
    "name": "保护箱安装（客户提供）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_440",
    "name": "充电桩保护外箱（不锈钢）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_441",
    "name": "充电桩立柱",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_442",
    "name": "吊筋特殊环境（丝杆）",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_443",
    "name": "墙面线管开槽（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_444",
    "name": "墙面钻孔（厚度<40CM）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_445",
    "name": "墙面钻孔（厚度>40CM）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 60.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_446",
    "name": "断路器（空气开关）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_447",
    "name": "普通土路地面线管开挖（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_448",
    "name": "桥架 50mm*50mm*1.2mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_449",
    "name": "水泥/地砖地面线管开挖（含恢复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_450",
    "name": "浇筑充电桩立柱水泥墩",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 250.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_451",
    "name": "立柱安装（客户提供）",
    "unit": "台",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_452",
    "name": "线缆升级 3*10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_453",
    "name": "线缆升级 3*16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 65.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_454",
    "name": "线缆敷设 YJV-0.6/1kV-3*6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "西安领充",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_455",
    "name": "远程服务费（超出30公里）",
    "unit": "公里",
    "costPrice": null,
    "customerPrice": 4.0,
    "brand": "西安领充",
    "freeQuota": 30,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_456",
    "name": "预埋接地线（有接地极免费）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_457",
    "name": "高空作业费（4米及以上）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "西安领充",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
