import type { Material } from "../types/material"

export const addonMaterials_batch7Part1: Material[] = [
  {
    "id": "addon_294",
    "name": "专业开孔（墙体开孔孔径≤32mm，墙体厚度>40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_295",
    "name": "专业开孔（墙体开孔孔径≤32mm，墙体厚度≤40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_296",
    "name": "保护箱安装人工费（客户提供保护箱）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_297",
    "name": "充电桩保护箱（保护箱规格：600*500*250mm，厚度≥0.8mm，材质：冷轧钢）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_298",
    "name": "充电桩桩体拆除（仅含充电桩桩体拆除，适用于维修、移桩场景）",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_299",
    "name": "充电桩桩体挂桩（仅含充电桩桩体挂桩及调试，适用维修、移桩场景）",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_300",
    "name": "充电桩水泥基础（浇筑充电桩立柱水泥墩，≥300*200*200mm，含预埋螺栓）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_301",
    "name": "充电桩立柱（立柱规格：高度≥1.5m，材质：冷轧钢）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_302",
    "name": "充电桩线缆拆除（仅含线缆、套管等其他辅材拆除，适用于维修、移桩场景）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_303",
    "name": "充电桩线缆敷设（安装敷设原有线缆，含辅材及人工费，适用维修、移桩场景）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 18.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_304",
    "name": "单相漏电保护器（移桩后新地址安装/质保期外维修需更换漏电保护器）",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_305",
    "name": "单相空气开关（安装正泰或德力西2P空气开关25A/40A）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_306",
    "name": "吊丝固定（适用于室外架空线缆固定，仅包含吊丝、辅材及人工安装费用）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_307",
    "name": "吊筋固定（适用于地下小区车库架空线管固定，仅包含吊筋、辅材及人工安装费用）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_308",
    "name": "套包内线缆升级 3*6mm²升至3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_309",
    "name": "套包内线缆升级 3*6mm²升至3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_310",
    "name": "套包外线缆敷设 ZC-YJV-3*10mm²（含线缆、套管、辅材、人工及2年质保）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "比亚迪",
    "freeQuota": 0,
    "source": "addon"
  }
]
