import type { Material } from "../types/material"

export const addonMaterials_batch14Part1: Material[] = [
  {
    "id": "addon_224",
    "name": "30米套包内线缆升级至3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_225",
    "name": "专业开孔（砖墙/混凝土，限墙厚40cm/洞径11cm以下）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_226",
    "name": "充电桩保护箱（不锈钢 600*800*250mm）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_227",
    "name": "充电桩立柱混凝土基础浇筑（350*350*200mm，含挖坑/立柱安装）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 260.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_228",
    "name": "喷塑桥架安装（50*50*1.2mm，含材料及人工）",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_229",
    "name": "承重路开挖（含水泥路面修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 240.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_230",
    "name": "接地线（电阻≤4Ω，导电良好，工作接地）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_231",
    "name": "普通土地开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_232",
    "name": "普通水泥/砖路面开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_233",
    "name": "超30米电缆敷设 YJV 3*10mm²（含管及人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_234",
    "name": "超30米电缆敷设 YJV 3*6mm²（含PVC/镀锌管及人工）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_235",
    "name": "铺砖庭院开挖含修复（复合石料地面）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_236",
    "name": "铺砖庭院开挖含修复（花岗岩/高贵资砖地面）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 240.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_237",
    "name": "高空作业费（离地≥5米，按线缆长度计）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽埃安",
    "freeQuota": 0,
    "source": "addon"
  }
]
