import type { Material } from "../types/material"

export const addonMaterials_batch14Part2: Material[] = [
  {
    "id": "addon_357",
    "name": "50*50mm*1.2mm桥架",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_358",
    "name": "ZR-YJV3*10mm²电缆、镀锌管或PVC管、人工及四年质保",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_359",
    "name": "ZR-YJV3*16mm²电缆、镀锌管或PVC管、人工及四年质保",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 74.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_360",
    "name": "ZR-YJV3*6mm²电缆、镀锌管或PVC管、人工及四年质保",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_361",
    "name": "充电桩保护箱立柱（含安装）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_362",
    "name": "充电桩枪头锁材料及安装（机械密码锁）",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_363",
    "name": "墙体开孔φ32（砖、混凝土墙体）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_364",
    "name": "德力西220V单相有功功率电度表（DDS606 10(40)A）",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_365",
    "name": "接地极（φ8圆钢或截面大于100mm²角钢）",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_366",
    "name": "普通土质路面土方开挖及修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_367",
    "name": "水泥、沥青、地砖路面开挖及水泥修复",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_368",
    "name": "理想专属定制充电桩保护箱",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_369",
    "name": "电度表箱（用于单独安装电度表场景，符合防护标准）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_370",
    "name": "超过5米以上高空作业（最高1000元封顶）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "理想",
    "freeQuota": 0,
    "source": "addon"
  }
]
