import { Material } from '../types/material'

export const addonMaterials_batch12: Material[] = [
  {
    "id": "addon_542",
    "name": "一体式保护箱+立柱 7kW",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 550.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_543",
    "name": "上门检测费",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_544",
    "name": "代办电力报装（其他地区）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_545",
    "name": "代办电力报装（北京）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 600.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_546",
    "name": "充电桩保护盒 7kW",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 450.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_547",
    "name": "充电桩移机",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_548",
    "name": "其他材料（膨胀螺丝/尼龙膨胀/铜鼻子等）",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 0.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_549",
    "name": "打吊丝",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 20.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "HANGER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_550",
    "name": "打地极",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_551",
    "name": "打墙洞/穿墙孔",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_552",
    "name": "普通土地开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 30.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_553",
    "name": "普通水泥/砖路面开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 90.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_554",
    "name": "桥架及安装 50x50mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_555",
    "name": "沥青路面开挖（含修复）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_556",
    "name": "混凝土基础浇筑 400x350x350",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_557",
    "name": "混凝土基础浇筑 600x440x370",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_558",
    "name": "电表 40A单相",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "METER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_559",
    "name": "电表箱 PZ30",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 40.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_560",
    "name": "空气开关 220V 40A 2P",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_561",
    "name": "空气开关 220V 40A 2P带漏保",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 85.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_562",
    "name": "空气开关 4P40A带漏保",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 110.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_563",
    "name": "空气开关 4P40A带漏保（升级款）",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 180.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_564",
    "name": "立柱（普通款）7kW",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_565",
    "name": "立柱（直流款）20kW",
    "unit": "根",
    "costPrice": null,
    "customerPrice": 650.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_566",
    "name": "线缆铺设 ZR-YJV 3x10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_567",
    "name": "线缆铺设 ZR-YJV 3x16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 70.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_568",
    "name": "线缆铺设 ZR-YJV 3x6mm²",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 40.0,
    "brand": "领克",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_569",
    "name": "线缆铺设 ZR-YJV 5x10mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 75.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_570",
    "name": "线缆铺设 ZR-YJV 5x16mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 90.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_571",
    "name": "线缆铺设 ZR-YJV 5x6mm²",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 55.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_572",
    "name": "高空作业费（5米及以上）",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 35.0,
    "brand": "领克",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_481",
    "name": "保护箱安装",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_482",
    "name": "勘测（两次以上）",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "阿维塔",
    "freeQuota": 1,
    "category": "SERVICE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_483",
    "name": "墙体开孔>40mm",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_484",
    "name": "墙体开孔≤40mm",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 100.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_485",
    "name": "拆桩",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "REMOVE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_486",
    "name": "挂桩",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "INSTALL",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_487",
    "name": "接地极及安装",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 200.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "GROUND",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_488",
    "name": "断路器2P 40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 80.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_489",
    "name": "断路器4P 40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 140.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_490",
    "name": "桥架50*50*1.0mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_491",
    "name": "水泥路面开挖",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_492",
    "name": "沥青路面开挖",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 150.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_493",
    "name": "泥土路面开挖",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 45.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_494",
    "name": "混凝土基础",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "FOUNDATION",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_495",
    "name": "漏保40A",
    "unit": "个",
    "costPrice": null,
    "customerPrice": 260.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_496",
    "name": "电缆ZR-YJV-3*6",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 45.0,
    "brand": "阿维塔",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_497",
    "name": "电缆ZR-YJV-5*4",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "阿维塔",
    "freeQuota": 30,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_498",
    "name": "电缆升级",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "CABLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_499",
    "name": "立柱",
    "unit": "项",
    "costPrice": null,
    "customerPrice": 300.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "POLE",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_500",
    "name": "管线拆除",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 10.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_501",
    "name": "管线敷设",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 18.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_502",
    "name": "线管φ32mm",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 7.0,
    "brand": "阿维塔",
    "freeQuota": 30,
    "category": "PVC",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_503",
    "name": "维修人工",
    "unit": "次",
    "costPrice": null,
    "customerPrice": 400.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "OTHER",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_504",
    "name": "铺砖路面开挖",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 120.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_505",
    "name": "防护箱",
    "unit": "套",
    "costPrice": null,
    "customerPrice": 350.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "BOX",
    "source": "addon",
    "isFixed": true
  },
  {
    "id": "addon_506",
    "name": "高空作业",
    "unit": "米",
    "costPrice": null,
    "customerPrice": 50.0,
    "brand": "阿维塔",
    "freeQuota": 0,
    "category": "HIGH_ALTITUDE",
    "source": "addon",
    "isFixed": true
  }
]
