import type { Material } from "../types/material"

export const addonMaterials_batch6Part2: Material[] = [
  {
    "id": "addon_205",
    "name": "电缆敷设(三项) YJV-5*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_206",
    "name": "电缆敷设(单项) YJV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_207",
    "name": "电缆敷设(单项) YJV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_208",
    "name": "电缆敷设(单项) YJV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_209",
    "name": "电缆桥架(100*50mm)",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_210",
    "name": "电表 220V 10(40)A单项",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_211",
    "name": "电表 380V 10(40)A三项",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_212",
    "name": "电表箱(PZ40)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_213",
    "name": "穿墙打孔 40-60cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_214",
    "name": "穿墙打孔 60-80cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_215",
    "name": "穿墙打孔 ≤40cm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_216",
    "name": "立柱安装(客户自备立柱)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_217",
    "name": "立柱水泥基础(400*300*400mm)",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_218",
    "name": "路面开槽及恢复 土路/草地",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_219",
    "name": "路面开槽及恢复 水泥路",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_220",
    "name": "路面开槽及恢复 铺砖庭院",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_221",
    "name": "防雨防盗箱(600*500*250mm,含安装)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_222",
    "name": "防雨防盗箱(仅安装)",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_223",
    "name": "高空作业(>5米)",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "广汽丰田",
    "freeQuota": 0,
    "source": "addon"
  }
]
