import type { Material } from "../types/material"

export const addonMaterials_batch10Part2: Material[] = [
  {
    "id": "addon_420",
    "name": "电缆敷设 YJV 3*6mm²（含人工）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_421",
    "name": "电缆敷设 YJV-0.6/1KV 3*10mm²（含人工）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_422",
    "name": "电缆敷设 YJV-0.6/1KV 3*16mm²（含人工）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_423",
    "name": "电缆桥架（布设50mm*100mm）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_424",
    "name": "移桩-充电桩体拆除",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_425",
    "name": "移桩-充电桩体拆除和挂装",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_426",
    "name": "移桩-充电桩体挂装",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_427",
    "name": "移桩-充电桩线缆拆除",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_428",
    "name": "移桩-充电桩线缆敷设（仅适用于维修、移桩场景）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 25.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_429",
    "name": "穿墙打孔（20cm<墙体厚度≤40cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_430",
    "name": "穿墙打孔（40cm<墙体厚度≤60cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_431",
    "name": "穿墙打孔（60cm<墙体厚度≤80cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_432",
    "name": "穿墙打孔（墙体厚度≤20cm）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_433",
    "name": "立柱安装（客户自购立柱，仅安装）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_434",
    "name": "钢结构底座制作及安装（400*330*150mm）",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_435",
    "name": "防撞警示柱（制作和安装）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_436",
    "name": "高空架设（电缆敷设5米及以上，1000元封顶）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "空灵零跑",
    "freeQuota": 0,
    "source": "addon"
  }
]
