import type { Material } from "../types/material"

export const addonMaterials_batch2Part2: Material[] = [
  {
    "id": "addon_60",
    "name": "高空作业",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "上汽通用",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_61",
    "name": "PVC管升级镀锌管",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_62",
    "name": "二次勘测上门服务费",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_63",
    "name": "保护箱安装（用户提供）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_64",
    "name": "充电桩保护外箱（不锈钢）",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_65",
    "name": "充电桩立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_66",
    "name": "充电桩立柱水泥墩",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 250.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_67",
    "name": "吊筋丝杆",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_68",
    "name": "墙面线管开槽（含恢复）",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_69",
    "name": "墙面钻孔（厚度<40CM）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_70",
    "name": "墙面钻孔（厚度>40CM）",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 60.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_71",
    "name": "断路器（空气开关）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_72",
    "name": "普通土路地面开挖（含恢复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_73",
    "name": "桥架 50*50*1.2mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_74",
    "name": "水泥/地砖地面开挖（含恢复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_75",
    "name": "立柱安装（用户提供）",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "台",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_76",
    "name": "线缆升级 YJV-0.6/1kV-3*10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_77",
    "name": "线缆升级 YJV-0.6/1kV-3*16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 65.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_78",
    "name": "线缆敷设 YJV-0.6/1kV-3*6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_79",
    "name": "远程服务费（超出30公里）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "公里",
    "costPrice": 0,
    "settlementPrice": 4.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_80",
    "name": "预埋接地线（有接地极免费）",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_81",
    "name": "高空作业费（4米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "五菱",
    "freeQuota": 0,
    "source": "addon"
  }
]
