import { Material } from '../types/material'

export const addonMaterials_batch12: Material[] = [
  {
    "id": "addon_542",
    "name": "一体式保护箱+立柱 7kW",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 550.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_543",
    "name": "上门检测费",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_544",
    "name": "代办电力报装（其他地区）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_545",
    "name": "代办电力报装（北京）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 600.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_546",
    "name": "充电桩保护盒 7kW",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 450.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_547",
    "name": "充电桩移机",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_548",
    "name": "其他材料（膨胀螺丝/尼龙膨胀/铜鼻子等）",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_549",
    "name": "打吊丝",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 20.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_550",
    "name": "打地极",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_551",
    "name": "打墙洞/穿墙孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_552",
    "name": "普通土地开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 30.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_553",
    "name": "普通水泥/砖路面开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_554",
    "name": "桥架及安装 50x50mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_555",
    "name": "沥青路面开挖（含修复）",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_556",
    "name": "混凝土基础浇筑 400x350x350",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_557",
    "name": "混凝土基础浇筑 600x440x370",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_558",
    "name": "电表 40A单相",
    "category": "电表",
    "categoryCode": "METER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_559",
    "name": "电表箱 PZ30",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_560",
    "name": "空气开关 220V 40A 2P",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_561",
    "name": "空气开关 220V 40A 2P带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 85.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_562",
    "name": "空气开关 4P40A带漏保",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 110.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_563",
    "name": "空气开关 4P40A带漏保（升级款）",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 180.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_564",
    "name": "立柱（普通款）7kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_565",
    "name": "立柱（直流款）20kW",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0,
    "settlementPrice": 650.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_566",
    "name": "线缆铺设 ZR-YJV 3x10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_567",
    "name": "线缆铺设 ZR-YJV 3x16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 70.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_568",
    "name": "线缆铺设 ZR-YJV 3x6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_569",
    "name": "线缆铺设 ZR-YJV 5x10mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_570",
    "name": "线缆铺设 ZR-YJV 5x16mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 90.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_571",
    "name": "线缆铺设 ZR-YJV 5x6mm²",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 55.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_572",
    "name": "高空作业费（5米及以上）",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 35.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "领克",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_481",
    "name": "保护箱安装",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_482",
    "name": "勘测（两次以上）",
    "category": "服务",
    "categoryCode": "SERVICE",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 1,
    "source": "addon"
  },
  {
    "id": "addon_483",
    "name": "墙体开孔>40mm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_484",
    "name": "墙体开孔≤40mm",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 100.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_485",
    "name": "拆桩",
    "category": "拆除",
    "categoryCode": "REMOVE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_486",
    "name": "挂桩",
    "category": "安装",
    "categoryCode": "INSTALL",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_487",
    "name": "接地极及安装",
    "category": "接地",
    "categoryCode": "GROUND",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 200.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_488",
    "name": "断路器2P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 80.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_489",
    "name": "断路器4P 40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 140.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_490",
    "name": "桥架50*50*1.0mm",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_491",
    "name": "水泥路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_492",
    "name": "沥青路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 150.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_493",
    "name": "泥土路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_494",
    "name": "混凝土基础",
    "category": "基础",
    "categoryCode": "FOUNDATION",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_495",
    "name": "漏保40A",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 0,
    "settlementPrice": 260.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_496",
    "name": "电缆ZR-YJV-3*6",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 45.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_497",
    "name": "电缆ZR-YJV-5*4",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_498",
    "name": "电缆升级",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_499",
    "name": "立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "项",
    "costPrice": 0,
    "settlementPrice": 300.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_500",
    "name": "管线拆除",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_501",
    "name": "管线敷设",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 18.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_502",
    "name": "线管φ32mm",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 7.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 30,
    "source": "addon"
  },
  {
    "id": "addon_503",
    "name": "维修人工",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "次",
    "costPrice": 0,
    "settlementPrice": 400.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_504",
    "name": "铺砖路面开挖",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 120.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_505",
    "name": "防护箱",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "套",
    "costPrice": 0,
    "settlementPrice": 350.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  },
  {
    "id": "addon_506",
    "name": "高空作业",
    "category": "高空",
    "categoryCode": "HIGH_ALTITUDE",
    "unit": "米",
    "costPrice": 0,
    "settlementPrice": 50.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": "阿维塔",
    "freeQuota": 0,
    "source": "addon"
  }
]
