import { Material } from '../types/material'

export const costMaterials: Material[] = [
  {
    "id": "cost_1",
    "name": "C25",
    "unit": "个",
    "costPrice": 26.8,
    "customerPrice": 26.8,
    "brand": null,
    "freeQuota": 0,
    "category": "OTHER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_2",
    "name": "C40",
    "unit": "个",
    "costPrice": 26.8,
    "customerPrice": 26.8,
    "brand": null,
    "freeQuota": 0,
    "category": "OTHER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_3",
    "name": "C40A",
    "unit": "个",
    "costPrice": 46.5,
    "customerPrice": 46.5,
    "brand": null,
    "freeQuota": 0,
    "category": "OTHER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_4",
    "name": "漏保盒",
    "unit": "个",
    "costPrice": 5.0,
    "customerPrice": 5.0,
    "brand": null,
    "freeQuota": 0,
    "category": "BREAKER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_6",
    "name": "PVC",
    "unit": "米",
    "costPrice": 1.0,
    "customerPrice": 1.0,
    "brand": null,
    "freeQuota": 0,
    "category": "PVC",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_7",
    "name": "专业开孔砖墙混凝土墙",
    "unit": "个",
    "costPrice": 0.0,
    "customerPrice": 0.0,
    "brand": null,
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_8",
    "name": "保护箱",
    "unit": "个",
    "costPrice": 75.0,
    "customerPrice": 75.0,
    "brand": null,
    "freeQuota": 0,
    "category": "BOX",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_10",
    "name": "保护箱安装费",
    "unit": "个",
    "costPrice": 0.0,
    "customerPrice": 0.0,
    "brand": null,
    "freeQuota": 0,
    "category": "BOX",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_13",
    "name": "吊丝",
    "unit": "套",
    "costPrice": 2.0,
    "customerPrice": 2.0,
    "brand": null,
    "freeQuota": 0,
    "category": "HANGER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_16",
    "name": "工单",
    "unit": "个",
    "costPrice": 10.0,
    "customerPrice": 10.0,
    "brand": null,
    "freeQuota": 0,
    "category": "OTHER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_17",
    "name": "开孔",
    "unit": "个",
    "costPrice": 0.0,
    "customerPrice": 0.0,
    "brand": null,
    "freeQuota": 0,
    "category": "WALL_DRILL",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_22",
    "name": "柏油",
    "unit": "米",
    "costPrice": 3.0,
    "customerPrice": 3.0,
    "brand": null,
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_23",
    "name": "桥架",
    "unit": "米",
    "costPrice": 7.0,
    "customerPrice": 7.0,
    "brand": null,
    "freeQuota": 0,
    "category": "BRIDGE",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_24",
    "name": "水泥",
    "unit": "米",
    "costPrice": 40.0,
    "customerPrice": 40.0,
    "brand": null,
    "freeQuota": 0,
    "category": "ROAD_OPEN",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_25",
    "name": "泡钉",
    "unit": "个",
    "costPrice": 25.0,
    "customerPrice": 25.0,
    "brand": null,
    "freeQuota": 0,
    "category": "OTHER",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_26",
    "name": "浪涌",
    "unit": "个",
    "costPrice": 37.0,
    "customerPrice": 37.0,
    "brand": null,
    "freeQuota": 0,
    "category": "SURGE",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_30",
    "name": "电缆",
    "unit": "米",
    "costPrice": 16.0,
    "customerPrice": 16.0,
    "brand": null,
    "freeQuota": 0,
    "category": "CABLE",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_32",
    "name": "立柱",
    "unit": "根",
    "costPrice": 75.0,
    "customerPrice": 75.0,
    "brand": null,
    "freeQuota": 0,
    "category": "POLE",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_33",
    "name": "立柱安装费",
    "unit": "根",
    "costPrice": 0.0,
    "customerPrice": 0.0,
    "brand": null,
    "freeQuota": 0,
    "category": "POLE",
    "source": "cost",
    "isFixed": true
  },
  {
    "id": "cost_38",
    "name": "镀锌管",
    "unit": "米",
    "costPrice": 3.5,
    "customerPrice": 3.5,
    "brand": null,
    "freeQuota": 0,
    "category": "PVC",
    "source": "cost",
    "isFixed": true
  }
]
