import { Material } from '../types/material'

export const costMaterials: Material[] = [
  {
    "id": "cost_1",
    "name": "C25",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 26.8,
    "settlementPrice": 26.8,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_2",
    "name": "C40",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 26.8,
    "settlementPrice": 26.8,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_3",
    "name": "C40A",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 46.5,
    "settlementPrice": 46.5,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_4",
    "name": "漏保盒",
    "category": "漏保",
    "categoryCode": "BREAKER",
    "unit": "个",
    "costPrice": 5.0,
    "settlementPrice": 5.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_6",
    "name": "PVC",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 1.0,
    "settlementPrice": 1.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_7",
    "name": "专业开孔砖墙混凝土墙",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0.0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_8",
    "name": "保护箱",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 75.0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_10",
    "name": "保护箱安装费",
    "category": "保护箱",
    "categoryCode": "BOX",
    "unit": "个",
    "costPrice": 0.0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_13",
    "name": "吊丝",
    "category": "吊筋",
    "categoryCode": "HANGER",
    "unit": "套",
    "costPrice": 2.0,
    "settlementPrice": 2.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_16",
    "name": "工单",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 10.0,
    "settlementPrice": 10.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_17",
    "name": "开孔",
    "category": "开孔",
    "categoryCode": "WALL_DRILL",
    "unit": "个",
    "costPrice": 0.0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_22",
    "name": "柏油",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 3.0,
    "settlementPrice": 3.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_23",
    "name": "桥架",
    "category": "桥架",
    "categoryCode": "BRIDGE",
    "unit": "米",
    "costPrice": 7.0,
    "settlementPrice": 7.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_24",
    "name": "水泥",
    "category": "路面",
    "categoryCode": "ROAD_OPEN",
    "unit": "米",
    "costPrice": 40.0,
    "settlementPrice": 40.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_25",
    "name": "泡钉",
    "category": "其他",
    "categoryCode": "OTHER",
    "unit": "个",
    "costPrice": 25.0,
    "settlementPrice": 25.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_26",
    "name": "浪涌",
    "category": "浪涌",
    "categoryCode": "SURGE",
    "unit": "个",
    "costPrice": 37.0,
    "settlementPrice": 37.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_30",
    "name": "电缆",
    "category": "线缆",
    "categoryCode": "CABLE",
    "unit": "米",
    "costPrice": 16.0,
    "settlementPrice": 16.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_32",
    "name": "立柱",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 75.0,
    "settlementPrice": 75.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_33",
    "name": "立柱安装费",
    "category": "立柱",
    "categoryCode": "POLE",
    "unit": "根",
    "costPrice": 0.0,
    "settlementPrice": 0.0,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  },
  {
    "id": "cost_38",
    "name": "镀锌管",
    "category": "管材",
    "categoryCode": "PVC",
    "unit": "米",
    "costPrice": 3.5,
    "settlementPrice": 3.5,
    "stock": 0,
    "minStock": 0,
    "isFixed": true,
    "brand": null,
    "freeQuota": 0,
    "source": "cost"
  }
]
